"""
Event Discovery Service - Integration wrapper for CrewAI agent
"""

import os
import json
import logging
from datetime import datetime
from typing import Dict, List
from sqlalchemy.orm import Session
from pathlib import Path
import glob

from app.models.database import User, UserProfile, Event, EventDiscoveryJob

logger = logging.getLogger(__name__)


class EventDiscoveryService:
    """Service to run event discovery and save results to database"""

    def __init__(self, db: Session):
        self.db = db

    def run_for_user(self, user_id: int) -> Dict:
        """
        Run event discovery for a user and save results to database

        Args:
            user_id: User ID to run discovery for

        Returns:
            Dictionary with job status and events found
        """
        try:
            # Get user and profile
            user = self.db.query(User).filter(User.id == user_id).first()
            if not user:
                raise ValueError(f"User {user_id} not found")

            profile = self.db.query(UserProfile).filter(UserProfile.user_id == user_id).first()
            if not profile:
                raise ValueError(f"User profile not found for user {user_id}")

            # Create job record
            job = EventDiscoveryJob(
                user_id=user_id,
                status="running",
                started_at=datetime.utcnow()
            )
            self.db.add(job)
            self.db.commit()
            self.db.refresh(job)

            logger.info(f"Starting event discovery for user {user_id}, job {job.id}")

            # Create temporary profile file for CrewAI agent
            profile_data = {
                "name": user.full_name,
                "email": user.email,
                "location": profile.location or "Global",
                "interests": profile.interests or [],
                "looking_for": profile.looking_for or [],
                "role": profile.role or "Professional",
                "company": profile.company or ""
            }

            # Import and run the agent
            from app.services.event_discovery_agent import EventDiscoveryAgent
            import tempfile

            # Create temp profile file
            with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False) as f:
                json.dump(profile_data, f, indent=2)
                temp_profile = f.name

            try:
                # Run the agent (will take a few minutes)
                agent = EventDiscoveryAgent()
                agent.run(temp_profile, user.email)

                # Parse the saved events file (agent saves to data/events/)
                project_root = Path(__file__).parent.parent.parent.parent
                events_dir = project_root / "data" / "events"
                event_files = sorted(glob.glob(str(events_dir / 'events_*.json')), reverse=True)

                if event_files:
                    with open(event_files[0], 'r') as f:
                        events_data = json.load(f)

                    # Upload JSON to S3 (if S3 storage is enabled)
                    from app.services.storage import get_storage_service
                    from app.core.config import settings
                    if settings.STORAGE_TYPE == "s3":
                        storage = get_storage_service("s3")
                        filename = f"events_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.json"
                        with open(event_files[0], 'rb') as f:
                            s3_path = storage.save_file(f, filename, user_id=user_id, data_type="events")
                        logger.info(f"Events JSON uploaded to S3: {s3_path}")

                        # Delete local file after S3 upload
                        os.remove(event_files[0])
                        logger.info(f"Local events file deleted: {event_files[0]}")

                    # Delete old events for this user before adding new ones
                    self._clear_old_events(user_id)

                    # Save events to database
                    events_saved = self._save_events_to_db(user_id, events_data)

                    # Update job
                    job.status = "completed"
                    job.events_found = events_saved
                    job.completed_at = datetime.utcnow()
                    self.db.commit()

                    logger.info(f"Event discovery completed for user {user_id}. Found {events_saved} events")

                    return {
                        "success": True,
                        "job_id": job.id,
                        "events_found": events_saved,
                        "message": f"Found {events_saved} relevant events"
                    }
                else:
                    raise Exception("No events file generated by agent")

            finally:
                # Clean up temp file
                if os.path.exists(temp_profile):
                    os.remove(temp_profile)

        except Exception as e:
            logger.error(f"Event discovery failed for user {user_id}: {e}", exc_info=True)

            # Update job as failed
            if 'job' in locals():
                job.status = "failed"
                job.error_message = str(e)
                job.completed_at = datetime.utcnow()
                self.db.commit()

            return {
                "success": False,
                "error": str(e),
                "message": "Event discovery failed"
            }

    def _clear_old_events(self, user_id: int):
        """Delete old events for a user before adding new ones"""
        try:
            deleted_count = self.db.query(Event).filter(
                Event.user_id == user_id
            ).delete()
            self.db.commit()
            logger.info(f"Deleted {deleted_count} old events for user {user_id}")
        except Exception as e:
            logger.error(f"Error clearing old events: {e}")
            self.db.rollback()

    def _save_events_to_db(self, user_id: int, events_data: Dict) -> int:
        """Save discovered events to database"""
        events_saved = 0

        priority_map = {
            "must_attend": 10,
            "should_attend": 5,
            "nice_to_attend": 1
        }

        for priority_level, events_list in events_data.items():
            if priority_level not in priority_map:
                continue

            if not isinstance(events_list, list):
                continue

            for event_obj in events_list:
                try:
                    # Extract exhibitor data
                    exhibitors_data = event_obj.get('exhibitors')
                    # If exhibitors is a string (like "not yet published"), convert to proper format
                    if isinstance(exhibitors_data, str):
                        exhibitors_json = {"status": exhibitors_data, "list": []}
                    elif isinstance(exhibitors_data, list):
                        exhibitors_json = {"status": "available", "list": exhibitors_data}
                    else:
                        exhibitors_json = {"status": "unknown", "list": []}

                    # Extract event details
                    event = Event(
                        user_id=user_id,
                        title=event_obj.get('event_name', event_obj.get('name', 'Untitled Event')),
                        description=event_obj.get('description', ''),
                        url=event_obj.get('registration_link', event_obj.get('url', '')),
                        date=event_obj.get('date', ''),
                        location=event_obj.get('location', ''),
                        event_type=event_obj.get('type', 'conference'),
                        relevance_score=event_obj.get('relevance_score', priority_map[priority_level]),
                        relevance_reason=event_obj.get('why_relevant', event_obj.get('reason', '')),
                        source="AI Discovery Agent",
                        matched_interests=event_obj.get('topics', event_obj.get('key_topics', [])),
                        exhibitors=exhibitors_json
                    )

                    self.db.add(event)
                    events_saved += 1

                except Exception as e:
                    logger.error(f"Error saving event: {e}")
                    continue

        self.db.commit()
        return events_saved

    def get_user_events(self, user_id: int, limit: int = 50) -> List[Event]:
        """Get events for a user"""
        return self.db.query(Event).filter(
            Event.user_id == user_id
        ).order_by(
            Event.relevance_score.desc(),
            Event.created_at.desc()
        ).limit(limit).all()

    def get_job_status(self, job_id: int) -> EventDiscoveryJob:
        """Get job status"""
        return self.db.query(EventDiscoveryJob).filter(
            EventDiscoveryJob.id == job_id
        ).first()